name: dailytrojan
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.2.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  html: ^0.15.5
  html_unescape: ^2.0.0
  flutter_widget_from_html: ^0.15.3
  share_plus: ^12.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_inappwebview: ^6.1.5
  responsive_grid: ^2.4.4
  flutter_svg: ^2.0.16
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_messaging: ^16.0.0
  firebase_core: ^4.0.0
  haptic_feedback: ^0.5.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - games/
    - games/troydle/
    - games/troydle/styles/
    - games/troydle/scripts/
    - games/troydle/imgs/
    - games/troydle/music/
    - games/troydle/dailytrojan-lib/
    - games/troydle/dailytrojan-lib/fonts/
    - games/troydle/dailytrojan-lib/fonts/GeistMono/
    - games/troydle/dailytrojan-lib/fonts/Inter/
    - games/troydle/dailytrojan-lib/fonts/Nunito/
    - games/troydle/dailytrojan-lib/fonts/SourceSerif4/
    - games/troydle/dailytrojan-lib/icons/
    - games/troydle/dailytrojan-lib/icons/fonts/
    - games/spelling-beads/
    - games/spelling-beads/styles/
    - games/spelling-beads/scripts/
    - games/spelling-beads/imgs/
    - games/spelling-beads/dailytrojan-lib/
    - games/spelling-beads/dailytrojan-lib/fonts/
    - games/spelling-beads/dailytrojan-lib/fonts/GeistMono/
    - games/spelling-beads/dailytrojan-lib/fonts/Inter/
    - games/spelling-beads/dailytrojan-lib/fonts/Nunito/
    - games/spelling-beads/dailytrojan-lib/fonts/SourceSerif4/
    - games/spelling-beads/dailytrojan-lib/icons/
    - games/spelling-beads/dailytrojan-lib/icons/fonts/
    - assets/logo/logo.svg

  fonts:
    - family: DailyTrojanIcons
      fonts:
        - asset: fonts/DailyTrojanIcons.ttf
    - family: SourceSerif4
      fonts:
        - asset: fonts/SourceSerif4-Regular.ttf
        - asset: fonts/SourceSerif4-Italic.ttf
          style: italic
        - asset: fonts/SourceSerif4-Bold.ttf
          weight: 700
        - asset: fonts/SourceSerif4-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Italic.ttf
          style: italic
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-BoldItalic.ttf
          weight: 700
          style: italic