name: dailytrojan
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.2.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  html: ^0.15.5
  html_unescape: ^2.0.0
  flutter_widget_from_html: ^0.15.3
  share_plus: ^10.1.2
  flutter_launcher_icons: ^0.14.1
  flutter_inappwebview: ^6.1.5
  responsive_grid: ^2.4.4
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - games/
    - games/bandle/
    - games/bandle/styles/
    - games/bandle/scripts/
    - games/bandle/imgs/
    - games/bandle/music/
    - games/bandle/dailytrojan-lib/
    - games/bandle/dailytrojan-lib/fonts/
    - games/bandle/dailytrojan-lib/fonts/GeistMono/
    - games/bandle/dailytrojan-lib/fonts/Inter/
    - games/bandle/dailytrojan-lib/fonts/Nunito/
    - games/bandle/dailytrojan-lib/fonts/SourceSerif4/
    - games/bandle/dailytrojan-lib/icons/
    - games/bandle/dailytrojan-lib/icons/fonts/
    - games/spelling-beads/
    - games/spelling-beads/styles/
    - games/spelling-beads/scripts/
    - games/spelling-beads/imgs/
    - games/spelling-beads/dailytrojan-lib/
    - games/spelling-beads/dailytrojan-lib/fonts/
    - games/spelling-beads/dailytrojan-lib/fonts/GeistMono/
    - games/spelling-beads/dailytrojan-lib/fonts/Inter/
    - games/spelling-beads/dailytrojan-lib/fonts/Nunito/
    - games/spelling-beads/dailytrojan-lib/fonts/SourceSerif4/
    - games/spelling-beads/dailytrojan-lib/icons/
    - games/spelling-beads/dailytrojan-lib/icons/fonts/

  fonts:
    - family: SourceSerif4
      fonts:
        - asset: fonts/SourceSerif4-Regular.ttf
        - asset: fonts/SourceSerif4-Italic.ttf
          style: italic
        - asset: fonts/SourceSerif4-Bold.ttf
          weight: 700
        - asset: fonts/SourceSerif4-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Italic.ttf
          style: italic
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-BoldItalic.ttf
          weight: 700
          style: italic