name: dailytrojan
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.2.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  html: ^0.15.5
  html_unescape: ^2.0.0
  flutter_widget_from_html: ^0.15.3
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: SourceSerif4
      fonts:
        - asset: fonts/SourceSerif4-Regular.ttf
        - asset: fonts/SourceSerif4-Italic.ttf
          style: italic
        - asset: fonts/SourceSerif4-Bold.ttf
          weight: 700
        - asset: fonts/SourceSerif4-BoldItalic.ttf
          weight: 700
          style: italic