// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFvw1dKoiQDc5i61EOBUv9F45iJGOoAIg',
    appId: '1:287706234043:android:e6c6104c6477d222693d9e',
    messagingSenderId: '287706234043',
    projectId: 'dt-ancile-notifications',
    storageBucket: 'dt-ancile-notifications.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkXeeqOpLjhnvnNgdNy94QmYHFaQ8iyFY',
    appId: '1:287706234043:ios:673e16d108e53bfb693d9e',
    messagingSenderId: '287706234043',
    projectId: 'dt-ancile-notifications',
    storageBucket: 'dt-ancile-notifications.firebasestorage.app',
    iosBundleId: 'com.dailytrojan.mobile',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbMI4kVExesRIUM9Md4nD0HhrJ55DcGSI',
    appId: '1:287706234043:web:8fef801a9dddca59693d9e',
    messagingSenderId: '287706234043',
    projectId: 'dt-ancile-notifications',
    authDomain: 'dt-ancile-notifications.firebaseapp.com',
    storageBucket: 'dt-ancile-notifications.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkXeeqOpLjhnvnNgdNy94QmYHFaQ8iyFY',
    appId: '1:287706234043:ios:bf4c7954030aaf55693d9e',
    messagingSenderId: '287706234043',
    projectId: 'dt-ancile-notifications',
    storageBucket: 'dt-ancile-notifications.firebasestorage.app',
    iosBundleId: 'com.dailytrojan.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbMI4kVExesRIUM9Md4nD0HhrJ55DcGSI',
    appId: '1:287706234043:web:dafa25fd89478e83693d9e',
    messagingSenderId: '287706234043',
    projectId: 'dt-ancile-notifications',
    authDomain: 'dt-ancile-notifications.firebaseapp.com',
    storageBucket: 'dt-ancile-notifications.firebasestorage.app',
  );

}